/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.forms;

/**
 *
 * @author keijo
 */
public class TelaBotarHistorico extends javax.swing.JFrame {

    /**
     * Creates new form TelaBotarHistorico
     */
    public TelaBotarHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        txtAlergias = new javax.swing.JTextField();
        txtProblemas = new javax.swing.JTextField();
        txtConvênio = new javax.swing.JTextField();
        txtHospital = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setContentAreaFilled(false);
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 650, 120, 30));

        txtAlergias.setBackground(new java.awt.Color(132, 104, 148));
        txtAlergias.setBorder(null);
        getContentPane().add(txtAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 400, -1));

        txtProblemas.setBackground(new java.awt.Color(132, 104, 148));
        txtProblemas.setBorder(null);
        txtProblemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemasActionPerformed(evt);
            }
        });
        getContentPane().add(txtProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 400, -1));

        txtConvênio.setBackground(new java.awt.Color(132, 104, 148));
        txtConvênio.setBorder(null);
        getContentPane().add(txtConvênio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 400, -1));

        txtHospital.setBackground(new java.awt.Color(132, 104, 148));
        txtHospital.setBorder(null);
        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 400, -1));

        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 150, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add Informações.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed

    private void txtProblemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBotarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBotarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBotarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBotarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBotarHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAlergias;
    private javax.swing.JTextField txtConvênio;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtProblemas;
    // End of variables declaration//GEN-END:variables
}
