/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.forms;

import javax.swing.JOptionPane;

/**
 *
 * @author diego.sprado
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnCadAqui = new javax.swing.JButton();
        btnCadPro = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setBackground(new java.awt.Color(132, 104, 148));
        txtLogin.setText("Usuário");
        txtLogin.setBorder(null);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, 20));

        txtSenha.setBackground(new java.awt.Color(132, 104, 148));
        txtSenha.setText("senha");
        txtSenha.setBorder(null);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 400, -1));

        btnCadAqui.setBackground(new java.awt.Color(132, 104, 148));
        btnCadAqui.setText("Cadastre-se aqui");
        btnCadAqui.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadAqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAquiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadAqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 20));

        btnCadPro.setBackground(new java.awt.Color(132, 104, 148));
        btnCadPro.setText("Cadastre-se como profissional");
        btnCadPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 270, 20));

        btnEntrar.setBackground(new java.awt.Color(132, 104, 148));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 120, 30));

        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnCadAquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAquiActionPerformed
        TelaCadastro CadAqui = new TelaCadastro();
        this.dispose();  
        CadAqui.setVisible(true);  
    }//GEN-LAST:event_btnCadAquiActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
    String usuario = txtLogin.getText();
    String senha = String.valueOf(txtSenha.getPassword());

    // Verificar se os campos não estão vazios
    if(usuario.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    main.java.dao.LoginDAO loginDAO = new main.java.dao.LoginDAO();
    main.java.dao.LoginMedicoDAO loginMedicoDAO = new main.java.dao.LoginMedicoDAO();

    main.java.beans.Login usuários = loginDAO.autenticar(usuario, senha);
    main.java.beans.Medico medicos = loginMedicoDAO.autenticar(usuario, senha);

    // Verificar se o login foi bem-sucedido
    if (usuários != null) {
        // Sucesso no login
        JOptionPane.showMessageDialog(this, "Login bem-sucedido! Bem-vindo, " + usuários.getUsuario());

        //Abre a proxima tela principal
        TelaPrincipal principal = new TelaPrincipal();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela

        
    // Verificar se o login foi bem-sucedido
    }   if(medicos != null){
        // Sucesso no login
        JOptionPane.showMessageDialog(this, "Login bem-sucedido! Bem-vindo, " + medicos.getUsuario());

        //Abre a proxima tela principal
       TelaPrincipal principal = new TelaPrincipal();
       this.dispose();  // Fecha a tela de login
       principal.setVisible(true);  // Abre a próxima tela
        
        
    } else {
        // Falha no login
        JOptionPane.showMessageDialog(this, "Username ou senha incorretos. Tente novamente.");
        
    }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProActionPerformed
         TelaCadastroProfissional CadAqui = new TelaCadastroProfissional();
        this.dispose();  
        CadAqui.setVisible(true);  
    }//GEN-LAST:event_btnCadProActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAqui;
    private javax.swing.JButton btnCadPro;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
